wifi:
  ssid: !secret iot_ssid
  password: !secret iotnetwork_password
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: $devicename
    password: !secret ap_wifi
captive_portal:   #used so you can modify wifi/upload bin file etc.