time:
  - platform: homeassistant   #uses Home Assistant as time source
    id: homeassistant_time
    timezone: $timezone
        
text_sensor:
  - platform: template
    name: Uptime
    update_interval: $uptime_refresh
    entity_category: diagnostic
    icon: mdi:clock-start
    lambda: |-
      auto s = millis() / 1000;
      return str_snprintf("%02d:%02d:%02d:%02d", 11, s / 86400, s / 3600 % 24, s / 60 % 60, s % 60);
  - platform: template
    name: "Current Time"   #show current time of device
    lambda: |-
      char str[18];
      time_t currTime = id(homeassistant_time).now().timestamp;
      strftime(str, sizeof(str), "%y-%m-%d %H:%M:%S", localtime(&currTime));
      return  { str };
    update_interval: $uptime_refresh    
    entity_category: diagnostic
    icon: mdi:clock-outline



