# Config for Euri Lighting LIS-A1001
# https://templates.blakadder.com/euri_lighting_LIS-A1001.html


# Basic Config
esphome:
  name: $devicename
  platform: ESP8266
  board: esp01_1m
  comment: ${devicetype}  
 
logger:
light:
  - platform: rgb
    name: ${friendly_name} Color
    red: output_red
    green: output_green
    blue: output_blue
    default_transition_length: 1s
    restore_mode: RESTORE_DEFAULT_OFF

  - platform: cwww
    name: ${friendly_name} White
    warm_white: output_warm_white
    cold_white: output_cold_white
    cold_white_color_temperature: 6200 K
    warm_white_color_temperature: 2800 K
    default_transition_length: 1s
    restore_mode: RESTORE_DEFAULT_OFF


output:
  - platform: esp8266_pwm
    id: output_red
    pin: GPIO4
    max_power: 100%
    frequency: 100 Hz
  - platform: esp8266_pwm
    id: output_green
    pin: GPIO12
    max_power: 100%
    frequency: 100 Hz
  - platform: esp8266_pwm
    id: output_blue
    pin: GPIO14
    max_power: 100%
    frequency: 100 Hz
  - platform: esp8266_pwm
    id: output_warm_white
    pin: GPIO13
    max_power: 100%
    frequency: 1000 Hz
  - platform: esp8266_pwm
    id: output_cold_white
    pin: GPIO5
    max_power: 100%
    frequency: 1000 Hz

 
