substitutions:
  name: air-1-mk4s
  friendly_name: AIR-1-mk4s
  $devicename: air-1-mk4s
  $wifi_refresh: 120s
  static_ip: 192.168.100.23
  gateway: 192.168.100.1
  subnet: 255.255.255.0
  dns1: 192.168.50.13 
packages:
  ApolloAutomation.AIR-1: github://ApolloAutomation/AIR-1/Integrations/ESPHome/AIR-1.yaml
  wifi: !include .base-staticip-wifi-iot100.yaml

esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: !secret hass_encryption_key



