esphome:
  name: attic_node_garage
  platform: ESP8266
  board: d1_mini_pro

substitutions:
  devicename: attic_node_garage
  upper_devicename: "Attic Node Garage"
  friendly_name: Attic Node Garage
  wifi_refresh: 300sec
  uptime_refresh: 60sec
  timezone: America/Los_Angeles
  devicetype: ESP8266 d1_mini_pro

packages:
  wifi: !include .base-wifi.yaml
  web_server: !include .base-web_server.yaml
  hass_ota_base: !include .base-hass-ota.yaml
  update_sensors: !include .base-uptime-sensors.yaml  

wifi:
  ssid: !secret iot_ssid
  password: !secret iotnetwork_password
  domain: !secret domain
  fast_connect: false
  use_address: 192.168.50.116

# Enable logging
logger:

#i2c:
#  sda: 4
#  scl: 5
sensor:
  - platform: dht
    pin: D2
    model: am2302
    temperature:
      name: "$upper_devicename Temperature"
      unit_of_measurement: "°C"
    humidity:
      name: "$upper_devicename Humidity"
    update_interval: 60sec
  


