
substitutions:
  devicename: back-flood-left
  friendly_name: Back Flood Left
  timezone: America/Los_Angeles
  devicetype: Sonoff mini
  uptime_refresh: 300s
  wifi_refresh: 300s
# Set the restore mode for after power outage:  
# More info:  https://esphome.io/components/switch/gpio.html
  restore_mode: RESTORE_DEFAULT_OFF
  

packages:
  wifi: !include .base-wifi.yaml
  web_server: !include .base-web_server.yaml
  hass_ota_base: !include .base-hass-ota.yaml
  update_sensors: !include .base-uptime-sensors.yaml
  base_device: !include .device-sonoff_mini.yaml




