
substitutions:
  devicename: back-flood-right
  friendly_name: Back Flood Right
  hassname: Back-Flood-Right
  timezone: America/Los_Angeles
# Set the restore mode for after power outage:  
# More info:  https://esphome.io/components/switch/gpio.html
  restore_mode: RESTORE_DEFAULT_OFF
  

<<: !include .device-sonoff_mini.yaml
<<: !include .base-wifi.yaml
<<: !include .base-web_server.yaml
<<: !include .base-hass-ota.yaml




