substitutions:
  devicename: "shelly-plus-2pm"
  device_name_1: "Shelly Plus 2PM Switch 1"
  device_name_2: "Shelly Plus 2PM Switch 2"
  friendly_name: "Shelly Plus 2pm"
  output_name_1: "Output 1"
  output_name_2: "Output 2"
  input_name_1: "Input 1"
  input_name_2: "Input 2"
  timezone: America/Los_Angeles
  devicetype: Shelly Plus 2pm
  uptime_refresh: 60s
  wifi_refresh: 60s


  
packages:
  wifi: !include .base-wifi.yaml
  web_server: !include .base-web_server.yaml
  hass_ota_base: !include .base-hass-ota.yaml
  base_device: !include .device-shelly-plus-2pm.yaml
