substitutions:
  devicename: "first-shelly-plus-2pm"
  devicename_1: "First Device"
  devicename_2: "Second Device"
  #devicename_switch1: "First Shelly Plus 2PM Switch 1"
  #devicename_switch2: "First Shelly Plus 2PM Switch 2"
  friendly_name: "Shelly Plus 2pm"
  #devicename_output1: "Output 1"
  #devicename_output2: "Output 2"
  #devicesname_input1: "Input 1"
  #devicesname_input1: "Input 2"
# Relay trip limits
  max_power: "3600.0"
  max_temp: "80.0"
  timezone: America/Los_Angeles
  devicetype: Shelly Plus 2pm
  uptime_refresh: 60s
  wifi_refresh: 60s


  
packages:
  wifi: !include .base-wifi.yaml
  web_server: !include .base-web_server.yaml
  hass_ota_base: !include .base-hass-ota.yaml
  update_sensors: !include .base-uptime-sensors.yaml
  base_device: !include .device-shelly-plus-2pm.yaml
