substitutions:
  devicename: "garage-soffit-lights"
  friendly_name: Garage Soffit Lights
  timezone: America/Los_Angeles
  comment: Shelly Dimmer2 - dhcp - iotnet
  uptime_refresh: 60s
  wifi_refresh: 120s
  max_temp: "90.0"

packages:
  wifi: !include .base-wifi-iot100.yaml
  web_server: !include .base-web_server.yaml
  hass_ota_base: !include .base-hass-ota.yaml
  update_sensors: !include .base-uptime-sensors.yaml
  base_device: !include .device-shelly-dimmer-2.yaml
                           
  
