substitutions:
  name: "ht-back-right"
  devicename: "ht-back-right"  
  friendly_name: Home Theater Back Right
  timezone: America/Los_Angeles
  devicetype: Kauf Bulb BR30
  uptime_refresh: 60s
  wifi_refresh: 120s


packages:
  wifi: !include .base-wifi.yaml
  web_server: !include .base-web_server.yaml
  hass_ota_base: !include .base-hass-ota.yaml
  update_sensors: !include .base-uptime-sensors.yaml
  base_device: !include .device-kauf-rgbww-bulbs.yaml
  Kauf.RGBWW: github://KaufHA/kauf-rgbww-bulbs/kauf-bulb.yaml