substitutions:
  name: "ht-front-left"
  devicename: "ht-front-left"  
  friendly_name: Home Theater Front Left
  timezone: America/Los_Angeles
  devicetype: Kauf Bulb BR30
  uptime_refresh: 60s
  wifi_refresh: 120s
  static_ip: 192.168.51.109
  gateway: 192.168.50.1
  subnet: 255.255.254.0

esphome:
  name: ${name}
  name_add_mac_suffix: false
  comment: ${devicetype}
    
wifi:
  ssid: !secret iot_ssid
  password: !secret iotnetwork_password
  ap:
    ssid: $devicename
    password: !secret ap_wifi
  manual_ip:
    static_ip: $static_ip
    gateway: $gateway
    subnet: $subnet  
    dns1: 192.168.50.13    
captive_portal: 
#sensor:
#  - platform: wifi_signal
#    name: "${friendly_name} WiFi Signal"
#    device_class: signal_strength
#    update_interval: $wifi_refresh

#  - platform: uptime
#    name: "Uptime"
#    update_interval: $uptime_refresh

      
web_server:
  port: 80
  auth:
    username: !secret web_server_username
    password: !secret web_server_password

api:   #Enable API
#  encryption: 
#    key: !secret hass_encryption_key
  password: !secret api_password
ota:   #Enable OTA updates
  password: !secret ota_password

packages:
  
  Kauf.RGBWW: github://KaufHA/kauf-rgbww-bulbs/kauf-bulb.yaml