substitutions:
  devicename: kitchen-hotwater
  friendly_name: "Kitchen Hotwater"
  timezone: America/Los_Angeles
  devicetype: D1 Mini ESP32
  uptime_refresh: 300s
  wifi_refresh: 300s

esphome:
  name: ${devicename}
  name_add_mac_suffix: false
  comment: $devicetype
  friendly_name: $friendly_name

esp32:
  board: wemos_d1_mini32

dallas:
  - pin: GPIO19
    update_interval: 10s


sensor:
  - platform: dallas
    address: 0x760516a3682cff28
    name: "Kitchen Hotwater Temperature"
    unit_of_measurement: "°C"
    icon: "mdi:water-percent"
    device_class: "temperature"
    #state_class: "measurement"
    accuracy_decimals: 1
    


# Enable logging
logger:


packages:
  wifi: !include .base-wifi.yaml
  web_server: !include .base-web_server.yaml
  hass_ota_base: !include .base-hass-ota.yaml
  update_sensors: !include .base-uptime-sensors.yaml

