substitutions:
  name: "living-lamp-tall"
  devicename: "living-lamp-tall"
  friendly_name: Living Room Lamp Tall
  timezone: America/Los_Angeles
  devicetype: Kauf Bulb BLF10
  uptime_refresh: 60s
  wifi_refresh: 120s
  
esphome:
  name: ${name}
  name_add_mac_suffix: false
  comment: ${devicetype}
    
wifi:
  ssid: !secret iot_ssid
  password: !secret iotnetwork_password
  ap:
    ssid: $devicename
    password: !secret ap_wifi
captive_portal: 
sensor:
  - platform: wifi_signal
    name: "${friendly_name} WiFi Signal"
    device_class: signal_strength
    update_interval: $wifi_refresh

  - platform: uptime
    name: "Uptime"
    update_interval: $uptime_refresh

      
web_server:
  port: 80
  auth:
    username: !secret web_server_username
    password: !secret web_server_password

api:   #Enable API
  encryption: 
    key: !secret hass_encryption_key
  password: !secret api_password
ota:   #Enable OTA updates
  password: !secret ota_password

packages:
  
  Kauf.RGBWW: github://KaufHA/kauf-rgbww-bulbs/kauf-bulb.yaml