
substitutions:
  devicename: s31-not-configured
  friendly_name: Not Configured
  hassname: S31-Not-Configured
  timezone: America/Los_Angeles
  
# Set the restore mode for after power outage:  
# More info:  https://esphome.io/components/switch/gpio.html
  restore_mode: RESTORE_DEFAULT_ON
  

<<: !include .device-sonoff_s31.yaml
<<: !include .base-wifi.yaml
<<: !include .base-web_server.yaml
<<: !include .base-hass-ota.yaml




