substitutions:
  devicename: "shop-heater"
  friendly_name: Shop Heater
  timezone: America/Los_Angeles
  devicetype: Shelly 1PM
  uptime_refresh: 60s
  wifi_refresh: 120s
  sensor_refresh: 60s
  max_temp: "70.0"
  static_ip: 192.168.100.24
  gateway: 192.168.100.1
  subnet: 255.255.255.0
  dns1: 192.168.50.13 

packages:
  wifi: !include .base-staticip-wifi-iot100.yaml
  web_server: !include .base-web_server.yaml
  hass_ota_base: !include .base-hass-ota.yaml
  update_sensors: !include .base-uptime-sensors.yaml
  base_device: !include .device-shelly-1pm.yaml
                           
  
