
substitutions:
  devicename: washer-outlet
  friendly_name: Washer Outlet
  timezone: America/Los_Angeles
  comment: Sonoff S31 - dhcp - iotnet
  uptime_refresh: 60s
  wifi_refresh: 120s
  power_refresh: 60s

# Set the restore mode for after power outage:  
# More info:  https://esphome.io/components/switch/gpio.html
  restore_mode: RESTORE_DEFAULT_ON
  

packages:
  wifi: !include .base-wifi-iot100.yaml
  web_server: !include .base-web_server.yaml
  hass_ota_base: !include .base-hass-ota.yaml
  update_sensors: !include .base-uptime-sensors.yaml
  base_device: !include .device-sonoff_s31.yaml



